### ISSUE TITLE
backup script should be more robust

### ISSUE THREAD

**Issue by fvoges** [fvoges/puppet-pe_backup#5]
the current script 

 * [ ] #9 doesn't have proper error handling
 * [ ] #10 doesn't check if another script is already running
 * [ ] #11 doesn't cleanup if it's interrupted
 * [ ] #12 has minimal logging
